{
	"name": "svelte-error-boundary",
	"description": "Handle errors in Svelte components, preventing full app crashes.",
	"repo_url": "https://github.com/denisstasyev/svelte-error-boundary",
	"authors": ["denisstasyev"],
	"homepage": "https://github.com/denisstasyev/svelte-error-boundary#readme",
	"downloads": 29,
	"updated": "2021-06-21T05:54:20.359Z",
	"tags": ["miscellaneous"],
	"github_stars": 10,
	"typescript": false,
	"version": "1.0.2",
	"svelte_range": "latest",
	"last_rune_check_version": "1.0.2",
	"dependency_tree": {
		"rootIndex": 0,
		"packages": [
			{
				"name": "svelte-error-boundary",
				"version": "1.0.2",
				"size": 27023
			}
		],
		"dependencies": [],
		"circular": []
	},
	"readme": "# svelte-error-boundary\n\n[![NPM version](https://img.shields.io/npm/v/svelte-error-boundary.svg?style=flat)](https://www.npmjs.com/package/svelte-error-boundary) [![NPM downloads](https://img.shields.io/npm/dm/svelte-error-boundary.svg?style=flat)](https://www.npmjs.com/package/svelte-error-boundary) [![Svelte v3](https://img.shields.io/badge/svelte-v3-blueviolet.svg)](https://svelte.dev)\n\nPartly fix error boundary Svelte 3 problem to prevent full app crash on initialization\n\n# :warning: Warning: this package fixes only the problem with initialization errors. Runtime errors could not be handled with this approach\n\nThe key issue is that some of the built-in methods need to be wrapped in Svelte to create runtime error handling support, but there is only one pure \"true\" way to do this, and that is by implementing this built-in feature in Svelte.\n\nThere is another \"runtime\" error boundary package called [@crownframework/svelte-error-boundary](https://www.npmjs.com/package/@crownframework/svelte-error-boundary). But it also does not handle all errors due to this array of Svelte methods [GUARDED_BLOCK_FNS](https://github.com/CrownFramework/svelte-error-boundary/blob/main/src/createBoundary.js#L2), view [this issue](): \"That you for reporting this. This does indeed seem to be either a bug or – more likely – a limitation of the current implementation\". Another potential disadvantave of [@crownframework/svelte-error-boundary](https://www.npmjs.com/package/@crownframework/svelte-error-boundary) is too much more created `try...catch` blocks. This could affect the browser's built-in code optimizations. For example, according to this [Stack Overflow answer](https://stackoverflow.com/questions/19727905/in-javascript-is-it-expensive-to-use-try-catch-blocks-even-if-an-exception-is-n): \"The problem is that V8 didn't support it in their optimizing compiler until version 6 of the engine, so the entire containing function that syntactically contains a try catch will not be optimized\". And according [Wikipedia](https://en.wikipedia.org/wiki/Google_Chrome_version_history) V8 6.0 is equal to Chrome 60. The presence of a large number of `try...catch` blocks will slow down browsers younger than Chrome 60.\n\n## :cake: Features\n\nRight now Svelte 3 has no built-in error handling in components out of the box. To solve this issue this package was created inspired by [this thread](https://github.com/sveltejs/svelte/issues/3733).\n\n- Simply applies Javascript `try...catch` statement to child components :lock:\n- Easy to use (as traditional component)\n\n## Install\n\n```bash\nnpm i svelte-error-boundary\n```\n\n## Usage\n\n```html\n<script>\n  import ErrorBoundary from 'svelte-error-boundary'\n\n  ...\n</script>\n\n<ErrorBoundary name=\"custom try catch\">\n  <BrokenComponent />\n</ErrorBoundary>\n```\n\n## API\n\n### Parameters\n\n| Name        | Type     | Default     | Description                 |\n| ----------- | -------- | ----------- | --------------------------- |\n| name        | string   | `undefined` | Custom name for error scope |\n| handleError | function | `undefined` | Function to handle error    |\n\nFunction `handleError(error, name)` can be used to send error logs to server and so on.\n\nNote that this component does not support SSR (`svelte.compile` with option: `generate: 'ssr'`) and does not support hydration (`svelte.compile` with option: `hydratable: true`).\n\nPlease use this `ErrorBoundary` component directly over the `BrokenComponent`, otherwise errors may appear outside. You can manually test the `ErrorBoundary` component by inserting `throw new Error('test')` inside your component.\n\n## License\n\nMIT &copy; [Denis Stasyev](https://github.com/denisstasyev)\n",
	"legacy_svelte": false,
	"downloads_history": [
		[3589, 20],
		[3596, 35],
		[3603, 50],
		[3610, 57],
		[3617, 44],
		[3624, 27],
		[3631, 39],
		[3638, 29],
		[3645, 31],
		[3652, 18],
		[3659, 49],
		[3666, 63],
		[3673, 31],
		[3680, 38],
		[3687, 38],
		[3694, 48],
		[3701, 44],
		[3708, 39],
		[3715, 43],
		[3722, 36],
		[3729, 39],
		[3736, 30],
		[3743, 36],
		[3750, 30],
		[3757, 41],
		[3764, 28],
		[3771, 30],
		[3778, 41],
		[3785, 39],
		[3792, 47],
		[3799, 44],
		[3806, 29],
		[3813, 44],
		[3820, 18],
		[3827, 37],
		[3834, 38],
		[3841, 31],
		[3848, 42],
		[3855, 47],
		[3862, 45],
		[3869, 26],
		[3876, 22],
		[3883, 50],
		[3890, 26],
		[3897, 53],
		[3904, 61],
		[3911, 43],
		[3918, 31],
		[3925, 65],
		[3932, 83],
		[3939, 56],
		[3946, 47],
		[3953, 97],
		[3960, 100],
		[3967, 80],
		[3974, 36],
		[3981, 58],
		[3988, 63],
		[3995, 31],
		[4002, 23],
		[4009, 16],
		[4016, 13],
		[4023, 16],
		[4030, 12],
		[4037, 17],
		[4044, 8],
		[4051, 8],
		[4058, 18],
		[4065, 32],
		[4072, 43],
		[4079, 63],
		[4086, 36],
		[4093, 23],
		[4100, 58],
		[4107, 7],
		[4114, 29],
		[4121, 13],
		[4128, 15]
	],
	"esm": true,
	"cjs": false
}
